<?php
$content = file_get_contents("app/Http/Controllers/Admin/SeminarController.php");
$content = str_replace(
    "return back()->with(\"success\", \"Examiners assigned successfully.\");\n    }\n}",
    "return back()->with(\"success\", \"Examiners assigned successfully.\");\n    }\n\n    public function storeScore(Request \$request, \$eventId)\n    {\n        \$request->validate([\n            \"score\" => \"required|numeric|min:0|max:100\",\n            \"comments\" => \"nullable|string\"\n        ]);\n\n        \$event = DefenceEvent::findOrFail(\$eventId);\n        \n        if (now()->format(\"Y-m-d\") !== \$event->schedule_start->format(\"Y-m-d\")) {\n            return back()->with(\"error\", \"You can only grade the student on the exact day of their presentation.\");\n        }\n\n        \App\Models\Evaluation::updateOrCreate(\n            [\n                \"defence_event_id\" => \$event->id,\n                \"evaluator_id\" => auth()->id()\n            ],\n            [\n                \"score\" => [\"total\" => \$request->score],\n                \"comments\" => \$request->comments,\n                \"submitted_at\" => now(),\n            ]\n        );\n\n        return back()->with(\"success\", \"Marks saved successfully.\");\n    }\n\n    public function downloadAttendance()\n    {\n        \$events = DefenceEvent::where(\"type\", \"seminar\")\n            ->with([\"thesis.student.user\", \"panelMembers.user\", \"evaluations\"])\n            ->get();\n\n        \$headers = [\n            \"Content-type\" => \"text/csv\",\n            \"Content-Disposition\" => \"attachment; filename=seminar_attendance_\" . date(\"Y-m-d_H-i-s\") . \".csv\",\n            \"Pragma\" => \"no-cache\",\n            \"Cache-Control\" => \"must-revalidate, post-check=0, pre-check=0\",\n            \"Expires\" => \"0\"\n        ];\n\n        \$callback = function() use(\$events) {\n            \$file = fopen(\"php://output\", \"w\");\n            fputcsv(\$file, [\"Date\", \"Student\", \"Examiner\", \"Attendance Status\", \"Grade Given\"]);\n\n            foreach (\$events as \$event) {\n                foreach (\$event->panelMembers as \$member) {\n                    \$evaluation = \$event->evaluations->where(\"evaluator_id\", \$member->user_id)->first();\n                    \$status = \$evaluation ? \"Present\" : \"Absent\";\n                    \$grade = \$evaluation ? (\$evaluation->score[\"total\"] ?? \"N/A\") : \"N/A\";\n                    \n                    fputcsv(\$file, [\n                        \$event->schedule_start ? \$event->schedule_start->format(\"Y-m-d\") : \"N/A\",\n                        \$event->thesis->student->user->name ?? \"N/A\",\n                        \$member->user->name ?? \"N/A\",\n                        \$status,\n                        \$grade\n                    ]);\n                }\n            }\n            fclose(\$file);\n        };\n\n        return response()->stream(\$callback, 200, \$headers);\n    }\n}",
    $content
);
file_put_contents("app/Http/Controllers/Admin/SeminarController.php", $content);

